function selectROIs(acq, img, sliceNum, channelNum, smoothWindow, excludeFrames)
% selectROIs(acq, img, sliceNum, channelNum, smoothWindow, excludeFrames)
% All inputs except acquisition object are optional.
%
% GUI for sorting through pixel-pixel correlation matrices to select
% appropriate ROIs for an acquisition. Requires precalculated pixel
% covariance file generated by calcPxCov and a binary file representation
% of the movie as well (for rapid trace loading).
%
% The GUI consists of two windows: One for selecting ROIs and one that
% displays activity traces and neuropil/body comparisons.
%
% INPUTS:
%
% img - the overview image used to select spatial regions, but is not used
% in the actual calculation of ROIs or neuropil (i.e. you can do whatever
% you want to it and it won't screw up cell selection). Defaults to the
% square root of the mean image, processed with local adaptive histogram
% equalization
%
% smoothWindow - the length (not std!) of gaussian kernel used to smooth
% traces for display and for fitting neuropil subtraction coefficients
% (standard deviation of gaussian window equals (smoothWindow-1) / 5)
%
% USAGE:
%
% Click on overview image to evaluate a region of your image. Use scroll
% wheel to adjust # of clusters in current region.
%
% Use 'tab' to cycle through clusters.
%
% Use 'space' to select current cluster as a potential ROI. To select a
% neuropil region for this ROI, use 'tab' to cycle to the most appropriate
% cluster and press 'space' again.
%
% Use '1'-'9' to save an ROI. If this is done after selecting a neuropil
% pairing (see above), then that pairing will be saved with the ROI.
%
% Use 'backspace' to delete the last saved ROI.
%
% Right-click on an existin ROI in the overview image to delete or re-label
% that ROI.
%
% Use 'm' to initiate manual drawing of polygon ROI (adds polygon to
% current clustering results).

% Replace missing inputs with []. Actual input validation happens in
% selectRoisGui.m:
if ~exist('img','var')
    img = [];
end
if ~exist('sliceNum','var')
    sliceNum = [];
end
if ~exist('channelNum','var')
    channelNum = [];
end
if ~exist('smoothWindow','var')
    smoothWindow = [];
end
if ~exist('excludeFrames','var')
    excludeFrames = [];
end

% All the code for the GUI is in the class selectRoisGui:
sel = selectRoisGui(acq, img, sliceNum, channelNum, smoothWindow, excludeFrames);